_prefs: 
  mapid: ''
  saveCenter: true
_properties: {}
attribution: ''
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -121.2712
  - 43.7135
  - 13
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 14
minzoom: 0
name: ''
source: "mapbox:///mapbox.mapbox-terrain-v2,mapbox.mapbox-streets-v5"
styles: 
  - var.mss
  - base.mss
  - bg.mss
template: ''
